{
    'name': 'Purchase Order Report',
    'version': '1.0',
    'summary': 'Purchase Order Report',
    'category': 'Report',
    'author': 'SAIAIPL',
    'maintainer': 'Pradip',
    'website': 'www.saiaipl.com',
    'license': '',
    'depends': ['purchase','web','base','sale'],
    'data': ['report/purchase_order_main_report.xml',
             'report/purchase_report_menu.xml',
             'report/template_demo.xml',
            #  'views/purchase_order_line_view.xml',
             ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
